name: 'OpenClaw Bot'
description: 'AI-powered bot for your repo — heartbeats, mentions, issues, PRs'
inputs:
  anthropic_api_key:
    description: 'Anthropic API key'
    required: true
  model:
    description: 'Model to use'
    default: 'claude-sonnet-4-5-20250514'
runs:
  using: 'node20'
  main: 'dist/index.js'
