name: 'OpenClaw Bot'
description: 'AI-powered bot for your repo — runs real OpenClaw, the same agent that powers WhatsApp/Discord bots'
author: 'Offload My Work'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: true
  model:
    description: 'Claude model to use'
    default: 'claude-sonnet-4-20250514'
    required: false
  github_token:
    description: 'GitHub token for API access'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
